---
title: "For solve the questions of chapter10 in ISLR"
author: "*Kiseong Park; Doctor, Data scientist*"
date: "*Monday, May 13, 2019*"
output: html_notebook
---

**Q. 7**

```{r}
library(ISLR)

plot(dist(scale(USArrests))^2/as.dist(1- cor(t(scale(USArrests)))))
```

**Q. 8**

```{r}
pr.out <- prcomp(USArrests, scale = TRUE)
pr.out$sdev^2/sum(pr.out$sdev^2)

apply((scale(USArrests) %*% pr.out$rotation)^2, 2, sum)/sum(apply(as.matrix(scale(USArrests))^2, 2, sum))
```

**Q. 9**

```{r}
USA.hc <- hclust(dist(USArrests), method='complete')
plot(USA.hc)
cutree(USA.hc, 3)

plot(hclust(dist(scale(USArrests)), method='complete'))
```

**Q. 10**

```{r}
set.seed(2)
x <- matrix(rnorm(20 * 3 * 50, mean = 0, sd = 0.001), ncol = 50)
x[1:20, 2] <- 1
x[21:40, 1] <- 2
x[21:40, 2] <- 2
x[41:60, 1] <- 1
true.labels <- c(rep(1, 20), rep(2, 20), rep(3, 20))
```

```{r}
x.pca <- prcomp(x)

plot(x.pca$x[,1:2], col=1:3, pch=19)

x.k3 <- kmeans(x, 3, nstart = 20)
table(true.labels, x.k3$cluster)

x.k2 <- kmeans(x, 2, nstart = 20)
table(true.labels, x.k2$cluster)

x.k4 <- kmeans(x, 4, nstart = 20)
table(true.labels, x.k4$cluster)

km.out <- kmeans(x.pca$x[, 1:2], 3, nstart = 20)
table(true.labels, km.out$cluster)

km.sk3 <- kmeans(scale(x), 3, nstart = 20)
table(true.labels, km.sk3$cluster)

x
```

